version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/backend/deploy/

hooks:
  BeforeInstall:
    - location: scripts/backup.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user