spring:
  datasource:
    url: jdbc:mysql://db-linkjoa.cbsy8uk2et04.ap-northeast-2.rds.amazonaws.com:3306/linkjoaDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&maxAllowedPacket=16777215&characterEncoding=UTF-8&useUnicode=true
    username: linkjoa_admin
    password: linkjoa123!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      auto-commit: true
      minimum-idle: 5

  data:
    redis:
      host: 127.0.0.1
      port: 6379