
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/linkjoaDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&maxAllowedPacket=16777215
    url: jdbc:mysql://localhost:3307/linkjoaDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&maxAllowedPacket=16777215
    username: linkjoa_admin
    password: linkjoa123!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      auto-commit: true
      minimum-idle: 5