spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/linkjoaDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&maxAllowedPacket=16777215
    url: jdbc:mysql://localhost:3307/linkjoaDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&maxAllowedPacket=16777215
    username: linkjoa_admin
    password: linkjoa123!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      auto-commit: true
      minimum-idle: 5

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        connection:
          isolation: 3
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: samgyeopjoa@gmail.com
    password: mhvqizlobtavojpc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: 43.201.166.174
      port: 6379

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.hibernate.sql: DEBUG
