
spring:
  profiles:
    default: dev
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        connection:
          isolation: 3
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: samgyeopjoa@gmail.com
    password: mhvqizlobtavojpc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.hibernate.sql: DEBUG

server:
  port: 8081